composer require symfony/stopwatch 4.2.8
composer require symfony/console 4.2.8
composer require symfony/inflector 4.2.8
composer require symfony/property-access 4.2.8
composer require symfony/http-foundation 4.2.8
composer require symfony/event-dispatcher 4.2.8
composer require symfony/debug 4.2.8
composer require symfony/http-kernel 4.2.8
composer require symfony/security 4.2.8
composer require symfony/dependency-injection 4.2.8
composer require symfony/filesystem 4.2.8
composer require symfony/config 4.2.8
composer require symfony/security-bundle 4.2.8
composer require symfony/templating 4.2.8
composer require symfony/routing 4.2.8
composer require symfony/finder 4.2.8
composer require symfony/var-exporter 4.2.8
composer require symfony/cache 4.2.8
composer require symfony/framework-bundle 4.2.8
composer require symfony/validator 4.2.8
composer require symfony/twig-bridge 4.2.9
composer require symfony/twig-bundle 4.2.8
composer require symfony/options-resolver 4.2.8
composer require symfony/intl 4.2.8
composer require symfony/form 4.2.8
composer require symfony/var-dumper 4.2.8
composer require symfony/web-profiler-bundle 4.2.8
composer require symfony/monolog-bridge 4.2.8
composer require symfony/monolog-bundle 3.3.1
composer require symfony/debug-bundle 4.2.8
composer require symfony/yaml 4.2.8
composer require symfony/dotenv 4.2.8
composer require symfony/expression-language 4.2.8
composer require symfony/ldap 4.2.8
composer require symfony/serializer 4.2.8
composer require symfony/property-info 4.2.8
composer require symfony/serializer-pack 1.0.2
composer require symfony/translation 4.2.8
composer require symfony/web-link 4.2.8
composer require symfony/asset 4.2.8
composer require symfony/process 4.2.8
composer require symfony/dom-crawler 4.2.8
composer require symfony/http-client 4.2.8
composer require symfony/phpunit-bridge 4.2.8
composer require symfony/browser-kit 4.2.8
composer require symfony/css-selector 4.2.8
composer require symfony/web-server-bundle 4.2.8
  